{{- if .Values.busybox }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-secret-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-secret-validator
  template:
    metadata:
      labels:
        app: busybox-secret-validator
    spec:
      containers:
        - name: secret-validator
          image: "busybox"
          args: [ "sleep", "3600" ]  # Esto mantendrá el contenedor ejecutando
          env:
            - name: PINECONE_KEY
              valueFrom:
                secretKeyRef:
                  name: pinecone
                  key: apikey
            - name: PINECONE_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: pinecone
                  key: environment
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: apikey
{{- end }}                  

