apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "zahidgalea/powered-chatbot-app:{{ .Values.powered_chatbot_app.image_version }}"
          env:
            - name: EMBEDDING_ENDPOINT
              value: "http://embedding-api-service:{{ .Values.embedding.container_port }}"