apiVersion: apps/v1
kind: Deployment
metadata:
  name: powered-chatbot-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powered-chatbot-app
  template:
    metadata:
      labels:
        app: powered-chatbot-app
    spec:
      containers:
        - name: app
          image: "zahidgalea/powered-chatbot-app:{{ .Values.app_version }}"
          resources:
            requests:
              ephemeral-storage: "8Gi"
            limits:
              ephemeral-storage: "10Gi"
          env:
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pinecone
                  key: apikey
            - name: PINECONE_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: pinecone
                  key: environment
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: apikey
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slacktoken
                  key: slacktoken
          ports:
            - containerPort: {{ .Values.powered_chatbot_app.container_port }}
---
apiVersion: v1
kind: Service
metadata:
  name: powered-chatbot-app-service
spec:
  selector:
    app: powered-chatbot-app
  ports:
    - protocol: TCP
      port: {{ .Values.powered_chatbot_app.container_port }}
      targetPort: {{ .Values.powered_chatbot_app.container_port }}

