apiVersion: apps/v1
kind: Deployment
metadata:
  name: powered-chatbot-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powered-chatbot-app
  template:
    metadata:
      labels:
        app: powered-chatbot-app
    spec:
      containers:
        - name: app
          image: "zahidgalea/powered-chatbot-app:{{ .Values.powered_chatbot_app.image_version }}"
          env:
            - name: CHROMADB_HOST
              value: "chromadb-service"
            - name: CHROMADB_PORT
              value: "{{ .Values.chromadb.container_port }}"
          ports:
            - containerPort: {{ .Values.powered_chatbot_app.container_port }}