apiVersion: apps/v1
kind: Deployment
metadata:
  name: powered-chatbot-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powered-chatbot-app
  template:
    metadata:
      labels:
        app: powered-chatbot-app
    spec:
      containers:
        - name: app
          image: "zahidgalea/powered-chatbot-app:{{ .Values.app_version }}"
          env:
            - name: PINECONE_KEY
              valueFrom:
                secretKeyRef:
                  name: pineconekey
                  key: pineconekey.txt
            - name: PINECONE_ENVIRONMENT
              value: "gcp-starter"

          ports:
            - containerPort: {{ .Values.powered_chatbot_app.container_port }}