apiVersion: v1
kind: Service
metadata:
  name: powered-chatbot-app-service
spec:
  selector:
    app: powered-chatbot-app
  ports:
    - protocol: TCP
      port: {{ .Values.powered_chatbot_app.container_port }}
      targetPort: {{ .Values.powered_chatbot_app.container_port }}