apiVersion: v1
kind: PersistentVolume
metadata:
  name: index-data
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /chromadb-persistent-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: index-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi