apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
spec:
  selector:
    app: chromadb
  ports:
    - protocol: TCP
      port: {{ .Values.chromadb.container_port }}
      targetPort: {{ .Values.chromadb.container_port }}