apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui-app
  ports:
    - protocol: TCP
      port: {{ .Values.ui.container_port }}
      targetPort: {{ .Values.ui.container_port }}