{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
        - name: app
          image: "zahidgalea/chatbot-ui:{{ .Values.app_version }}"
          env:
            - name: CHATBOT_HOST
              value: "powered-chatbot-app-service"
            - name: CHATBOT_PORT
              value: "{{ .Values.powered_chatbot_app.container_port }}"
          ports:
            - containerPort: {{ .Values.ui.container_port }}
{{- end }}